"""Stable error and finding types used at safety boundaries."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Iterable


class ErrorCode(StrEnum):
    """Stable machine-readable Phase 1 error codes."""

    APPROVAL_DIGEST_MISMATCH = "APPROVAL_DIGEST_MISMATCH"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    APPROVAL_REVOKED = "APPROVAL_REVOKED"
    APPROVAL_SCOPE_MISMATCH = "APPROVAL_SCOPE_MISMATCH"
    APPROVAL_TARGET_MISMATCH = "APPROVAL_TARGET_MISMATCH"
    ACTOR_AUTHORITY_INVALID = "ACTOR_AUTHORITY_INVALID"
    ARTIFACT_REFERENCE_INVALID = "ARTIFACT_REFERENCE_INVALID"
    CANONICAL_FLOAT_FORBIDDEN = "CANONICAL_FLOAT_FORBIDDEN"
    CANONICAL_RECORD_MISMATCH = "CANONICAL_RECORD_MISMATCH"
    CANONICAL_TYPE_INVALID = "CANONICAL_TYPE_INVALID"
    CHECKPOINT_CONTENT_FORBIDDEN = "CHECKPOINT_CONTENT_FORBIDDEN"
    DUPLICATE_ID = "DUPLICATE_ID"
    EVENT_REFERENCE_MISSING = "EVENT_REFERENCE_MISSING"
    EVENT_TYPE_SEMANTICS_INVALID = "EVENT_TYPE_SEMANTICS_INVALID"
    HASH_CHAIN_INVALID = "HASH_CHAIN_INVALID"
    ID_INVALID = "ID_INVALID"
    LEDGER_CORRUPT_TAIL = "LEDGER_CORRUPT_TAIL"
    LEDGER_POST_WRITE_VERIFY_FAILED = "LEDGER_POST_WRITE_VERIFY_FAILED"
    LIFECYCLE_TRANSITION_INVALID = "LIFECYCLE_TRANSITION_INVALID"
    MANIFEST_HASH_MISMATCH = "MANIFEST_HASH_MISMATCH"
    MANIFEST_VERSION_INVALID = "MANIFEST_VERSION_INVALID"
    CONTEXT_AUTHORIZATION_DENIED = "CONTEXT_AUTHORIZATION_DENIED"
    CONTEXT_SENSITIVITY_EXCEEDED = "CONTEXT_SENSITIVITY_EXCEEDED"
    EVIDENCE_OBJECT_INVALID = "EVIDENCE_OBJECT_INVALID"
    DECISION_SUPERSESSION_CYCLE = "DECISION_SUPERSESSION_CYCLE"
    PATH_OUTSIDE_RUNTIME_ROOT = "PATH_OUTSIDE_RUNTIME_ROOT"
    PACKAGE_VERSION_IMMUTABLE = "PACKAGE_VERSION_IMMUTABLE"
    PROJECTION_TAMPERED = "PROJECTION_TAMPERED"
    PROTECTED_PATH_WRITE_DENIED = "PROTECTED_PATH_WRITE_DENIED"
    SCHEMA_ADDITIONAL_PROPERTY = "SCHEMA_ADDITIONAL_PROPERTY"
    SCHEMA_CONST = "SCHEMA_CONST"
    SCHEMA_ENUM = "SCHEMA_ENUM"
    SCHEMA_FORMAT = "SCHEMA_FORMAT"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    SCHEMA_LENGTH = "SCHEMA_LENGTH"
    SCHEMA_PATTERN = "SCHEMA_PATTERN"
    SCHEMA_REQUIRED = "SCHEMA_REQUIRED"
    SCHEMA_TYPE = "SCHEMA_TYPE"
    SCHEMA_UNSUPPORTED_KEYWORD = "SCHEMA_UNSUPPORTED_KEYWORD"
    SESSION_REFERENCE_MISSING = "SESSION_REFERENCE_MISSING"
    WORK_ITEM_TRANSITION_INVALID = "WORK_ITEM_TRANSITION_INVALID"


@dataclass(frozen=True, order=True)
class Issue:
    """One deterministic validation or recovery issue."""

    code: str
    path: str
    message: str


class VaultNextError(Exception):
    """Base error for an operation that did not safely complete."""


class ValidationError(VaultNextError):
    """A candidate or canonical record failed deterministic validation."""

    def __init__(self, issues: Iterable[Issue]):
        self.issues = tuple(sorted(issues))
        message = "; ".join(f"{issue.code}@{issue.path}" for issue in self.issues)
        super().__init__(message)


class LedgerCorruptionError(ValidationError):
    """A ledger does not consist entirely of a valid canonical chain."""
